### ISSUE TITLE
use .jsx file extension

### ISSUE THREAD

**Issue by ghost23** [reactjs/react-autocomplete#10]
Hi,

I would like to suggest to use the .jsx file extension for files with jsx syntax. It makes handling with build systems easier, at least for me.

**Comment by misuba** [comment]
YES PLEASE. I'm getting pushback on having our server-side JSX compiler just run on everything.

**Comment by jimfb** [comment]
You can always use the `-x jsx` flag for the transpiler, right?  If you want to use the `.jsx` suffix in your code (instead of `.js`), nothing stops you.

**Comment by misuba** [comment]
Really the thing to do here is have a checked-in compiled version of the JSX, and export that. Then nobody needs to switch compiler flags for the sake of any particular module.

**Comment by sprjr** [comment]
There are `build/` and `dist/` versions that ship now with out JSX, so this should be resolved.
