### ISSUE TITLE
npm start fails with rackt error on tag v0.1.4

### ISSUE THREAD

**Issue by frankpinto** [reactjs/react-autocomplete#107]
On trying to get the examples to work I tried `npm i && npm start` and it errored out. Relevant error messages:

> Failed at the react-autocomplete@0.1.4 start script 'rackt server'.
> Tell the author that this fails on your system:
>     rackt server

Upon trying `node_modules/rackt-cli/bin/rack server` I get the following error message:

> .../node_modules/rackt-cli/bin/../tasks/server: line 5: .../node_modules/rackt-cli/bin/..//node_modules/.bin/webpack-dev-server: No such file or directory

Local folder structure redacted for clarity.

Seems related to #51

**Comment by CMTegner** [comment]
a9a1b6b3e33afb4fe7c4a4c49fca2dfa08aaff1d fixed this issue. `npm install` on master should make `npm start` work again.
