### ISSUE TITLE
Static-data example doesn't work on tag v0.1.4

### ISSUE THREAD

**Issue by frankpinto** [reactjs/react-autocomplete#108]
I've recently adopted a codebase that uses v0.1.4 and so am trying to wrap my head around how it works. I downloaded the zip of the archive and opened `examples/static-data/index.html` in Chrome. According to the Network tab the following files 404:

* examples/\__build__/shared.js
* examples/\__build__/static-data.js

`static-data.js` is in the same folder so I could easily fix the path in index.html but I don't see `shared.js` anywhere. I tried `npm i && npm start` as mentioned in #46 but still no luck (I've reported that issue as well at #107).

**Comment by sprjr** [comment]
@frankpinto I don't recall there being any super breaking changes on the follow 2 releases. There _is_ some changes for the `1.0.0-rc*`, are you unable to upgrade?

**Comment by frankpinto** [comment]
@sprjr sure, I think I'm going to try that now anyway as there's also an issue on this tag with iPhones I just ran into. You can't select anything.

**Comment by frankpinto** [comment]
any changelog or upgrade gotchas?
