### ISSUE TITLE
Should your component be controlled?

### ISSUE THREAD

**Issue by blackrabbit99** [reactjs/react-autocomplete#113]
You works with controlled component  and update value via props.value
```
value={this.props.value}
```

May it would be better to use uncontrolled components approach when you set nothing except default value if it is needed?

```
return <input type="text" defaultValue="Hello!" />
```

And set value from dropdown box if an action happens.

**Comment by CMTegner** [comment]
What's the use-case for a non-controlled variant of this component? Wouldn't you want to be able to clear the input without having to destroy the entire component and re-render?

**Comment by blackrabbit99** [comment]
@CMTegner after exploring code deeper i found that it's hardly possible. But i'm sure refusing of using state could reduce re-render amount. Not critical for now.
