### ISSUE TITLE
Warning for React.findDOMNode deprecated

### ISSUE THREAD

**Issue by savinash47** [reactjs/react-autocomplete#117]
Can this be fixed? it is just a easy fix.

**Comment by Jezternz** [comment]
I am actually getting a console error that appears to be triggered when giving the autofocus focus, any ideas for a temporary fix?

`Autocomplete.js:317 Uncaught TypeError: React.findDOMNode is not a function`

**Comment by savinash47** [comment]
It's just that React.findDOMNode is deprecated and the Autocomplete.js should either use ReactDOM or just refer the node using ref. So I think this should be fixed by the owners of the library. Or we can just fix and raise a PR.

**Comment by savinash47** [comment]
I can see that React.findDOMNode is used on line 308 of Autocomplete.js. It should be fixed there.

**Comment by savinash47** [comment]
PR #116 has the fix

**Comment by Jezternz** [comment]
Sweet, thanks @savinash47, will look forward to this making it into next npm release :)

**Comment by blackrabbit99** [comment]
@savinash47 @Jezternz This fix is dangerous for developers who can't upgrade their React version. I guess this library have to support old React version till next major release.

**Comment by blackrabbit99** [comment]
@savinash47 @Jezternz Also I don't think this PR is good for this issue because it consists some other fixes that doesn't bind with current issue

**Comment by savinash47** [comment]
@blackrabbit99 This looks something like a middle line which should fix the issue.

**Comment by ilbonte** [comment]
fixed in 1.0.1: https://github.com/reactjs/react-autocomplete/commit/4dbd2116254541b736037086f815a035bd9fe84b#diff-5648fade62433e310736d05db473d931R317

**Comment by CMTegner** [comment]
As @ilbonte said, this was fixed and released in 1.0.1.
