### ISSUE TITLE
change url via onSelect

### ISSUE THREAD

**Issue by nemoo** [reactjs/react-autocomplete#118]
This is a usage question, not a bug report.

I want the browser to open a certain url (in the current window) when the user selects an item of the autocomplete.

My code looks like this: 
...
 onSelect={(value, item) => {
       	      const url = "/customer/" + item.id;
       	      window.location = url;}
 }
...
When an item is selected, nothing happens (the browser does not open the url). The weird thing is: When i place an alert("Hi") before the window.location assignment, it works (the browser does indeed open the url).

Any ideas what I am doing wrong? Thanks!

**Comment by blackrabbit99** [comment]
Can't reproduce your issue everything works as expected, could you please create online fiddle with this issue?

**Comment by nemoo** [comment]
Thanks ,I finally found the error on my side. The react component was contained also in a form. So hitting enter triggered a form submit in addition to triggering the onSelect callback. Removing the form fixed it.
