### ISSUE TITLE
add Option Categories

### ISSUE THREAD

**Issue by justjake** [reactjs/react-autocomplete#12]
Add option categories, so we can present users with different sorts of options. This is well-supported in  [other autocomplete widgets](http://jqueryui.com/autocomplete/#categories).

This will require abstracting away the code to get widget DOM elements a bit. Right now you can add arbitrary elements to the combobox, but focusNext() and focusPrevious() will focus them, and they can then be selected.

**Comment by CMTegner** [comment]
Support for this landed a while back. You now have separate control over the menu and each menu item, allowing `Autocomplete` to only listen to the events (hover, click, etc) it wants to act upon.
