### ISSUE TITLE
Should dist and build folders store in repo?

### ISSUE THREAD

**Issue by blackrabbit99** [reactjs/react-autocomplete#120]
Is it really needed to store it in repo, maybe setup build process on prepublish hook and store dist into gh-pages repo? If you agree I can send PR for it.

**Comment by sprjr** [comment]
This was discussed in #109 as well, and a PR would be useful if you'd like to open one up!

**Comment by CMTegner** [comment]
@blackrabbit99 gogogo! Let's see if we can get this sorted before 1.1 :)

**Comment by blackrabbit99** [comment]
@CMTegner  I'm thinking about build on postinstall hook is it ok for you?

**Comment by CMTegner** [comment]
@blackrabbit99 don't think that would work since `devDependencies` are not included by default. Did you mean `prepublish`?

**Comment by blackrabbit99** [comment]
@CMTegner  yeap, I think ```prepublish``` would be enough for simple build using browserify.

**Comment by Daniel15** [comment]
Yeah I don't think it makes sense to store `dist` in source control. It's totally fine (and in fact, highly encouraged) to offer a precompiled version, but that should be done through a proper release strategy such as npm or GitHub releases (or both, which is what I do for babel-standalone). Build artifacts don't belong in source control.

**Comment by CMTegner** [comment]
The transpiled source and UMD bundles have been removed from the repo and are only available from the npm package.
