### ISSUE TITLE
Autocomplete is not defined

### ISSUE THREAD

**Issue by kaanyilgin** [reactjs/react-autocomplete#122]
Hi. I'm using reactjs inside .net mvc project. I don't use any source management library like webpack or browserify. I'm trying to use react-autocomplete but I get an "Autocomplete is not defined" error. react-autocomple is imported before my component so Autocomplete is initilized before my component.

**Comment by CMTegner** [comment]
You're going to have to give us a lot more info. Try creating a reduced test case and upload it to GH as a gist or a repo. Make sure to include an example of how you're importing/including the `react-autocomplete` code, since it sounds like the module isn't being exposed to your code correctly.

**Comment by kaanyilgin** [comment]
I started to use webpack. It works fine now. Thanks.
