### ISSUE TITLE
Odd behaviour when using the keyboard to navigate results

### ISSUE THREAD

**Issue by katgironpe** [reactjs/react-autocomplete#133]
It's odd that `down` arrow key doesn't work while `up` arrow key does. 
https://reactcommunity.org/react-autocomplete/custom-menu/

The default seems to be reverse. 
I'm not sure if this can be a function off the autocomplete feature. 
I could try later. 

Done exactly the same thing with Backbone.js last year.

**Comment by katgironpe** [comment]
@CMTegner Talking about the normal way of navigating a list a with a keyboard. It doesn't work. I'm gonna test later. Considering the design requirements, I'm going the path of rolling my own. I'm used to working on Backbone.js components for autocomplete. Another requirement is this has to flawlessly work on mobile. I'm not sure this does that.

**Comment by CMTegner** [comment]
>Talking about the normal way of navigating a list a with a keyboard.

Yep, that part I understood. What I don't get is in what environment you're seeing the errors, and your comment about backbone.js. Have you seen similar problems with autocomplete inputs built in backbone?

**Comment by katgironpe** [comment]
@CMTegner I am using Firefox 47.0 to test. Confirming this is an issue with https://reactcommunity.org/react-autocomplete/custom-menu/. It's not updated. I testing locally. The behaviour is great! Saves me a lot of time! THANK YOU!
