### ISSUE TITLE
Update gh-pages branch

### ISSUE THREAD

**Issue by CMTegner** [reactjs/react-autocomplete#134]
@sprjr I think I just realised how we can bring https://reactcommunity.org/react-autocomplete/ up to speed with master. Try running `rackt pages` in this repo. It should build the examples, nuke the current `gh-pages` branch, then create a new one and push it to gh. Hopefully that'll do the trick.

**Comment by sprjr** [comment]
Well I did that, and it may / may not have worked. See also: https://twitter.com/sprjrx/status/753269609180991489

**Comment by CMTegner** [comment]
Hah :p Well it looks like that did the trick 👍
