### ISSUE TITLE
React AutoComplete Scrollbar not working when parent element has 'tabindex="-1"' attribute

### ISSUE THREAD

**Issue by powercoder23** [reactjs/react-autocomplete#144]
The Scrollbar for the listed items is not working when parent element has `tabindex="-1"` attribute.

Thanks,
Dhiraj Gupta

**Comment by powercoder23** [comment]
Anyone?

**Comment by CMTegner** [comment]
Hi @powercoder23! Could you create a reduced test case/example for this? A gist or an example repo would be very helpful to get this problem solved!
