### ISSUE TITLE
Menu does not closing after selecting one. onliy ie

### ISSUE THREAD

**Issue by kortv** [reactjs/react-autocomplete#153]
When you try to select one item from the menu, the menu is not locked. For me this is a problem on the IE11 in other browsers work fine.
This can be demonstrated in ie11 using the examples linked on the site: 
https://reactcommunity.org/react-autocomplete/async-data/

**Comment by Zara603** [comment]
I have the same problem, only in IE.

**Comment by kortv** [comment]
[Here](https://github.com/reactjs/react-autocomplete/pull/154/files) simple solution of this problem.
So i have change Autocomplete component for my needs, and it's work fine.
That's happening cause IE focus() work, a little bit different, not like in over browsers

**Comment by CMTegner** [comment]
Thanks for brining this to our attention! I solved the problem in a slightly different way to prevent having to introduce a timeout. I tested it in IE11 on Windows 8.1 and it seems to work fine. A new release should be on npm in a couple of days. /cc @sprjr

**Comment by Zara603** [comment]
@CMTegner Thanks for the fixation. lodash has been removed from dependencies, though. I was getting ReferenceError: _ is not defined.

**Comment by Zara603** [comment]
@CMTegner I still have this problem on IE that the item is not selected.

**Comment by CMTegner** [comment]
>lodash has been removed from dependencies, though. I was getting ReferenceError: _ is not defined.

The lodash dependency was removed over two months ago. Which version of react-autocomplete are you running?

>I still have this problem on IE that the item is not selected.

Do you mean that the menu isn't closing? The fix hasn't been released on npm yet, so I assume you're building from master, correct?

**Comment by Zara603** [comment]
@CMTegner after I've updated from 0.2.1 to 1.1.0 I'm getting ReferenceError: _ is not defined

**Comment by CMTegner** [comment]
You're going to have to open a new issue and provide a reduced test case for us to help you further.

**Comment by dennisat** [comment]
I still have this issue. in IE11 and Edge only. version 1.7.2
