### ISSUE TITLE
Replace rackt-cli

### ISSUE THREAD

**Issue by CMTegner** [reactjs/react-autocomplete#161]
From #159:

> I should probably elaborate a little: I noticed that `npm start` no longer works because babel v5 doesn't recognize `presets` at the top level in `.babelrc`. I'm getting pretty tired of having to deal with weird build issues due to - amongst others - mismatch between our local babel version and the one that `rackt-cli` is running. I don't really want to do the counter-intuitive thing and downgrade ours, so I'd rather replace the entire setup with something more simple:
> - babel-cli to transpile the source
> - browserify to create UMD bundles and build/run examples
> - A simple, npm-run-script-powered deployment:
>   - npm version <version>
>   - npm run build
>   - npm publish

The tentative plan is to replace `rackt-cli`, removing `build/` and `dist/` from this repo, and hopefully end up with a setup which leads to less publish errors and fewer out-of-sync situations.

**Comment by sprjr** [comment]
Do you have any ideas on what you'd like the new process to _be_? I have some time this week to work on something like this (if you'd like) - I typically just use gulp/browserify/babel to produce the bundle via npm tasks, as well as prepublish hooks to ensure things line up better - but I don't do any of the git/gh-pages stuff automatically.

**Comment by CMTegner** [comment]
The WIP branch is here: https://github.com/reactjs/react-autocomplete/commits/replace-rackt-cli

The only challenge left is to figure out what to do with the UMD build. Webpack's UMD wrapper is a bit more lenient than browserify's, in that it lets the `require()` calls bubble all the way up to window/global. However, from what I can tell the current UMD bundle in this repo won't work with other CJS code, since it requires "React" and "ReactDOM", as apposed to "react" and "react-dom".

The UMD version in my branch leaves the require names as is (i.e. "react" and "react-dom"), which will work well for CJS and AMD, while exposing Autocomplete as "ReactAutocomplete" on the global scope (if no `require` is found). The downside is that if there's no `require()` found in the global scope the module will fail when it tries to fetch its dependencies, since it doesn't support searching window/global for deps (and even if it did they would most likely be defined as `window.React` and `window.ReactDOM`, not `window.react`/`window.react-dom`).

**Comment by CMTegner** [comment]
(the README explains most of what I've done)

**Comment by CMTegner** [comment]
Fixed in 82cd86e5e5adf2a575b7e0d031b262ab783c7346.
