### ISSUE TITLE
Examples are missing

### ISSUE THREAD

**Issue by Prophet32j** [reactjs/react-autocomplete#164]
When I try and access the examples I get a 404. Am I an idiot or is there a problem?

**Comment by CMTegner** [comment]
Hey! No, you're not derping, the examples are in fact temporarily broken :o We're working on it, hopefully they'll be back online shortly.

**Comment by CMTegner** [comment]
@sprjr I need some help here. I've updated the `gh-pages` branch, and everything looks fine, but all the files in `__build__` are 404ing, which leads me to believe something went wrong with the Jekyll build. I don't have access to the repo's settings page, so I can't view the build status.

**Comment by sprjr** [comment]
Ah shoot! I'll take a look - at a wedding in SD this weekend so hopefully tomorrow on the flight back. Could we possibly just compile them and use the new statics GH-pages / docs folder feature?

**Comment by CMTegner** [comment]
>Could we possibly just compile them and use the new statics GH-pages / docs folder feature?

Yeah, that's exactly what I was thinking! It would make updating the "homepage" a lot easier since everything's on the same branch, and we could compile the examples together with the main build.

**Comment by sprjr** [comment]
@CMTegner sorry I didn't get to this Sunday, have been catching up on a few work things and have not been able to get this on the daily todo.

**Comment by CMTegner** [comment]
@sprjr any progress on this? Perhaps we should just switch to using `/docs` instead? (I don't have access to do this btw., no pressure ;))

**Comment by Daniel15** [comment]
https://reactcommunity.org/react-autocomplete/static-data/ works fine for me, even though the gh-pages branch hasn't changed since September. Maybe it fixed itself? 😕

**Comment by CMTegner** [comment]
@Daniel15 looks like it just magically started working again. Very strange.
