### ISSUE TITLE
Menu doesn't render in the right place on scroll or resize

### ISSUE THREAD

**Issue by thatneat** [reactjs/react-autocomplete#166]
## summary
The styling used to keep the dropdown menu attached to the input is not robust and it misbehaves in some pretty reasonable scenarios.

### environment
Observed on Windows 10/Chrome 52.0.something

## repro 1
1. open the [static data example](https://reactcommunity.org/react-autocomplete/static-data/) in a small window (this will need to be an OS with resizable windows) - small enough to limit the flow of content
2. Type 'm' in the autocomplete box so that the menu shows with lots of options
3. Maximize the window or enter full-screen mode
**expected behavior**:
menu stays 'attached' to the input element

### actual behavior
Due to the way it's styled, the menu will move relative to the input component
![Bad behavior on resize](https://cloud.githubusercontent.com/assets/3341011/18412079/0541702c-773b-11e6-8232-25dba2c7abdb.png)

## repro 2
A related issue happens if you scroll when the menu is open. In this case, I added some extra `<p>`s and used a small portal to allow scrolling the example:
![Bad behavior on scroll](https://cloud.githubusercontent.com/assets/3341011/18412103/87b94f5c-773b-11e6-87b4-2e19c96bda05.png)

**Comment by thatneat** [comment]
I see that position:fixed is being used to allow the menu to appear without causing other contents to reflow. Another option - instead of using `position:fixed` and setting `top` and `left` by sleight-of-hand, use `position:static` (the default), don't try to set `top` and `left`, and instead set a negative `margin-bottom` equal to the height of the menu (the hard part).

**Comment by CMTegner** [comment]
You can override all menu styles via `props.menuStyle`. Alternatively you can implement the entire menu via `props.renderMenu`.

[We're aware](https://github.com/reactjs/react-autocomplete/pulls?q=is%3Apr+is%3Aopen+label%3Amenu-style) that the default menu styles aren't perfect, and we plan on addressing the issue as soon as we get other, more pressing issues out of the way. Until then, just use [the various props](https://github.com/reactjs/react-autocomplete/blob/master/lib/Autocomplete.js#L9:L26) to customise the component to satisfy your needs.

**Comment by livemixlove** [comment]
The default style is OK if you don't scroll, but otherwise it's broken.   For anyone coming here because the dropdown loses it's position on scroll, you could use this menuStyle (not thoroughly browser tested!) :

```
 {
		  borderRadius: '3px',
		  boxShadow: '0 2px 12px rgba(0, 0, 0, 0.1)',
		  background: 'rgba(255, 255, 255, 0.9)',
		  padding: '2px 0',
		  fontSize: '90%',
		  position: 'absolute',
		  top: '35px', // height of your input
		  left: 0,
		  overflow: 'auto',
		  width: '100%',
		}
```
And make sure to override the default renderMenu without this.style  to ignore the automatic top and left css properties.

 ```
const renderMenu = function(items, value, style) {
		  return <div className="autocomplete-dropdown-menu" style={{...this.menuStyle}} children={items}/>
		}
```

**Comment by CMTegner** [comment]
You can't evaluate `position: absolute` in a vacuum, since it will always be relative to its parents. This is my advice if you want to use the default styles:

```js
wrapperStyle: {
  display: 'inline-block',
  position: 'relative',
},
renderMenu (items, value) {
  return <div style={{...this.menuStyle}} children={items}/>
},
menuStyle: {
  borderRadius: '3px',
  boxShadow: '0 2px 12px rgba(0, 0, 0, 0.1)',
  background: 'rgba(255, 255, 255, 0.9)',
  padding: '2px 0',
  fontSize: '90%',
  position: 'absolute',
  width: '100%',
  overflow: 'auto',
},
```
