### ISSUE TITLE
Update Readme?

### ISSUE THREAD

**Issue by tiemevanveen** [reactjs/react-autocomplete#171]
Maybe it's good to update the readme with the following:
- Is this component ready to use or still a bit WIP? (10k downloads on npm last month)
- Which branch should be used to target PR's to

**Comment by tiemevanveen** [comment]
Keep up the good work btw, the component works great! 🎉

**Comment by CMTegner** [comment]
1) The README is definitely in need of some love, as it is quite conservative in its wording. I personally use `Autocomplete` for a range of production applications without any problems. That being said, we still have a lot of work ahead of us.
2) `master`

**Comment by tiemevanveen** [comment]
Check. Thanks

**Comment by CMTegner** [comment]
The readme has seen a lot of love lately. AFAIK this issue is no longer applicable. Just reopen if I'm wrong!
