### ISSUE TITLE
How to let the position of the list items be relative?

### ISSUE THREAD

**Issue by Stephenxiaoxiao** [reactjs/react-autocomplete#172]
How to let the position of the list items be relative? When I reduce the size of the window, the position of the list items does not change. Could someone here solve my problem? Thanks : )

**Comment by CMTegner** [comment]
Hi Stephen. Try this:

```jsx
<Autocomplete
  wrapperStyle={{ position: 'relative' }}
  menuStyle={{ position: 'absolute' }}
  ...
/>
```
