### ISSUE TITLE
Current build of dist/react-autocomplete.js does not seem to be honoring inputProps.onKeyUp

### ISSUE THREAD

**Issue by rroppolo** [reactjs/react-autocomplete#177]
In the current master, the inputProps can contain an onKeyUp callback, which is registered like:
onKeyUp={this.composeEventHandlers(this.handleKeyUp, inputProps.onKeyUp)}

However, it looks like this feature is not available in the current build under /dist.  (https://github.com/reactjs/react-autocomplete/blob/master/dist/react-autocomplete.js)
inputProps.onKeyUp and the composeEventHandlers function do not seem to be present in the current built version.  Could you please update the files under /dist to reflect the latest master?

Thanks!

**Comment by CMTegner** [comment]
Hi! That's correct, the newest code on `master` was not yet published. But it is now! Check out 1.4.0. You should be able to pass any event handler via `props.inputProps`.
