### ISSUE TITLE
Use component as select

### ISSUE THREAD

**Issue by judikdavid** [reactjs/react-autocomplete#178]
Hi,

is there an easy way to use react-autocomplete as a select component? 
I mean clear the input on onBlur if the input value is not from the items prop?

Or would you recommend an another solution or lib for this?

**Comment by CMTegner** [comment]
There's a couple of ways to do this:

1) Use `props.open` to keep the menu open until the user selects a valid option. You can disable the  surrounding form in the meantime to prevent submitting invalid data.
2) Use `props.inputProps.onBlur` to clear the input (by updating `props.value`) if it contains an invalid value.

Both of these options assume you're able to validate the input value against the available options.
