### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by cajoy** [reactjs/react-autocomplete#179]
Seems like module is not compatible with Typescript...

Is it going to be implemented in a future?

**Comment by moaead** [comment]
just do
const Autocomplete = require("react-autocomplete") as any;

no intellisense / typescript features, but works fine

**Comment by CMTegner** [comment]
@cajoy I'm not intimately familiar with TS, care to shed some light on what's not working?

**Comment by cdeutsch** [comment]
I think he's just saying Typings are missing (they can be added [independently and outside](https://github.com/typings/typings) this NPM, or inside the NPM via a `.d.ts` file)

What @moaead will allow you to use this component without typings.

**Comment by CMTegner** [comment]
@cdeutsch that's what I suspected.

There are no immediate plans to add typings, so I'll close this issue for now (under the assumption that `Autocomplete` works fine with TypeScript).

If someone wants to contribute typings (and take the time to learn us how to keep them updated) we'd be more than happy to review a PR.
