### ISSUE TITLE
utils.js in npm package?

### ISSUE THREAD

**Issue by Daniel15** [reactjs/react-autocomplete#183]
The npm package for this library ships with `utils.js` (ie. at `node_modules\react-autocomplete\lib\utils.js` after installing the package) which has utility methods that are probably only useful for the examples and unit tests. To me it seems like this isn't useful to end-users of the library and thus shouldn't be bundled with the release. 

What do you think?

**Comment by CMTegner** [comment]
Fixed in [3dd8fc81](https://github.com/reactjs/react-autocomplete/commit/3dd8fc813be6f08f5abede8602304e3e62cb647f). Thanks for pointing this out!
