### ISSUE TITLE
Track filteredItems as internal state, so as not to depend on `value` to trigger render?

### ISSUE THREAD

**Issue by natevw** [reactjs/react-autocomplete#189]
For an interface I am building, I would like the user to be able to chose multiple items from a long list. Basically once they find and select an item, I then add it to a separate list (and clear the search box), which renders to show which have already been selected and lets them user remove unwanted items too.

This component would almost serve my needs as an auto-suggesting search box, but all my own app logic is implemented on top of Redux via purely functional React components (`let MyComponent = props => <element/>`). I really have no need to track user's current search string in my app's own state, and since the Autocomplete component manages a lot of its own state internally anyway it'd be nice to leave this as basically an [uncontrolled component](https://facebook.github.io/react/docs/uncontrolled-components.html).

I started something of a branch (sorry not on GitHub, just hacked it into a local install within my project to quick test) with the following changes:

* removed the `value: ''` item from the object returned by `getDefaultProps`
* switched every use of `this.props.value` (except when rendering the input itself) to use `this.refs.input.value` instead
* do not provide any `value` property when I render an `<Autocomplete …/>` element

This mostly worked, *except* that the menu rendering falls behind my input. It's almost as if it gets rendered for the previous value, each time I type a new character (although `maybeAutoCompleteText` is using the latest value in its match).

I think what's happening is that without me re-rendering the component as I would do if I were displaying a new (managed) `<Autocomplete value=… …/>`, there's nothing to reliably trigger a re-render of the menu even if the result of `getFilteredItems()` changes. If the `filteredItems` result were "cached" within the components state, I think the corresponding `setState` call would allow this component to work properly with "unmanaged" input values.

**Comment by CMTegner** [comment]
We converted `Autcomplete` from an unmanaged to a managed control about [a year ago](https://github.com/reactjs/react-autocomplete/commit/c98f03889b8d59a84d42a2a694b5697dbb72c48e). The problem we had back then was that the component was basically useless for anyone who needed a managed control. After the change you could still use it unmanaged by creating a simpe wrapper:

```jsx
class UnmanagedAutocomplete extends Component {
  state = { value: this.props.initialValue }
  render() {
    return (
      <Autocomplete
        value={this.state.value}
        onChange={event => this.setState({ value: event.target.value })}
        onSelect={value => this.setState({ value })}
        {...this.props}
      />
    )
  }
}
```

I've been thinking of seeing if we can add support back for unmanaged use, but I haven't had the time of motivation for it yet.
