### ISSUE TITLE
Placeholder text

### ISSUE THREAD

**Issue by DagF** [reactjs/react-autocomplete#190]
Would be nice to be able to pass a placeholder text to the input element.

<input placeholder="text">

**Comment by DagF** [comment]
Would have made a patch for it myself if i could get the project to run.

I get the same error for all of the examples:
ERROR in ./examples/static-data/app.js
Module build failed: ReferenceError: [BABEL] /.../react-autocomplete/examples/static-data/app.js: Unknown option: /.../react-autocomplete/.babelrc.presets

If you have any idea of what can cause this I'll have another go. If not I'll have to way til after my exams before I try again.

**Comment by CMTegner** [comment]
Hi!

You can use `props.inputProps` to provide props to the `<input>` element:

```jsx
<Autocomplete
  inputProps={{ placeholder: 'Helpful examples' }}
/>
```

We're aware of the build problems. A workaround is to delete `.babelrc`.

**Comment by DagF** [comment]
Ah, sorry, I was not aware of that.

Thank you for a great module!

**Comment by CMTegner** [comment]
No worries, happy to help :) Once we land the 2.0 API you'll be able to use `Autocomplete` just as you would an `<input>`, i.e. we'll pass along any top-level props that aren't custom directly to the wrapped `<input>`.
