### ISSUE TITLE
Bug: Menu gets triggered by ARROW LEFT and ARROW RIGHT keys

### ISSUE THREAD

**Issue by CroniD** [reactjs/react-autocomplete#192]
Hi there,

currently if someone press ARROW LEFT or ARROW RIGHT key while the focus is on the input field, the highlight in the menu disappear. Tested with the static data example. It doesn't matter if there is some text in the field or not, I didn't inspect this issue any further, there might be more related background issues.

**Comment by CMTegner** [comment]
Thanks for letting us know! This was fixed in 5d61876fa5a96114d65dbfa3a0a85e3257a415ca which is a part of 1.4.4.
