### ISSUE TITLE
Bug: Menu doesn't scroll with the input field

### ISSUE THREAD

**Issue by CroniD** [reactjs/react-autocomplete#193]
Hi there,

if one modifies the static data example so that it's contains some space (whatever the content actually is) and a scrollbar will be shown, one can type in some characters, so that the menu will be visible, and scroll the page. The menu will remain at a fixed position and suddenly detach from the input field.

My fix would be: change the "position" value from "fixed" to "absolute" in Autocomplete.js line 48.

**Comment by CMTegner** [comment]
Hi!

Thanks for taking the time to report this (and the other issues).

We're aware that the default menu styles cause a [fair bit of headache](https://github.com/reactjs/react-autocomplete/labels/menu-style). The best bet is to use `props.menuStyle`/`props.renderMenu` to customize the menu and its styles to your needs.
