### ISSUE TITLE
IE8 compatibility

### ISSUE THREAD

**Issue by stebunovd** [reactjs/react-autocomplete#20]
I managed to get it working in IE8, actually just a few changes were needed: https://github.com/ivelum/react-autocomplete/compare/ivelum:de209bc...daf45ad

I would happy to make a PR, but not sure if this repository is still maintained. @ryanflorence are you interested in patches like this?

**Comment by rxaviers** [comment]
FWIW, I'd leave including `es5-shim` a decision up to the developer/user.

**Comment by CMTegner** [comment]
AFAIK this component works as long as it's run in a ES5 environment. As @rxaviers said, polyfilling/shimming is left up to the consumer.
