### ISSUE TITLE
Update to ES6

### ISSUE THREAD

**Issue by freestylebit** [reactjs/react-autocomplete#203]
I came across this component, and it works great!  I intend on submitting an enhancement PR, but noticed that the code is still using 0.14.7 as a dependency.

Are there plans to eventually update the library to use ES6 like the recommendation from the react team for future versions (> 15, 16)?

**Comment by CMTegner** [comment]
Hi! We'll probably transition to the class syntax once we start work on 2.0. Is there currently anything hindering you from submitting a PR? As far as I know we're not using any deprecated/removed APIs, so this component should work fine on both 0.14 and 15.

**Comment by freestylebit** [comment]
Not at the moment.  I just wasn't sure what the the next steps are for this project, so wanted to confirm before I proceed.

Thanks!
