### ISSUE TITLE
Error item Value.toLowerCase is not a function in Autocomplete.js function maybeAutoCompleteText

### ISSUE THREAD

**Issue by danielCrespo01** [reactjs/react-autocomplete#204]
The function maybeAutoCompleteText generates error itemValue.toLowerCase is not a function

**Comment by CMTegner** [comment]
Hi! That probably means `props.getItemValue()` isn't returning a string (which it should). Could you provide a example/reduced test case so we can help further?

**Comment by danielCrespo01** [comment]
I am using in the prop item an array of objects with the following structure:
`[{Id: 0, name: 'test'}]`
In the prop of getItemValue modify it as follows to return all values of the object:
`GetItemValue = {(item) => item}`
In the prop of sortItems I am using the following function I added some validations of input data:
```
_sortValues (a, b, value) {
If (! _ IsObject (a) ||! _. IsObject (b) || _.isObject (value)) return;
Return
A.name.toString () .ToLowerCase (). IndexOf (value.toString () .toLowerCase ())> b.name.toString () .toLowerCase (). IndexOf (value.toString () .toLowerCase ())? eleven
)
}
```
In the prop of shouldItemRender I am using the following function I added some input data validations:
```
_matchStateToTerm (state, value) {
If (! _. IsObject (state) || _.isObject (value)) return;
Return
State.name.toString () .ToLowerCase (). IndexOf (value.toString () .ToLowerCase ())! == -1
)
}
```

**Comment by CMTegner** [comment]
If your `items` array looks like you described then `getItemValue` should be `item => item.name`.

**Comment by danielCrespo01** [comment]
It is possible in the onSelect event to get the selected object not the name prop

**Comment by CMTegner** [comment]
Not sure if that's a question or not, but yes, the `onSelect` event handler receives the selected item as its only argument.

**Comment by danielCrespo01** [comment]
When putting in` getItemValue: {item => item.name}`
The onSelect function returns me the string name of the field not the object it suggests to me in this case?

**Comment by CMTegner** [comment]
Sorry, my mistake. The `onSelect` event handler receives two arguments: the string value displayed in the input, and the selected item, as [documented here](https://github.com/reactjs/react-autocomplete#onselect-function-optional).

**Comment by danielCrespo01** [comment]
Thank you very much solved subject with the item parameter of the onSelect function.

**Comment by jackie-d** [comment]
Thanks, actually may worth to highlight this specification on the doc or provide a related example, would be nice for a smooth start.
