### ISSUE TITLE
can the renderItem add the 'index' params

### ISSUE THREAD

**Issue by eruca** [reactjs/react-autocomplete#208]
I want the item render with the order number, like this 1 - Item, next 2-Item
```javascript
var element = this.props.renderItem(
        item,
        index, // add this one for format output
        this.state.highlightedIndex === index,
        {cursor: 'default'}
      )
```

**Comment by CMTegner** [comment]
Hi! This is on the list of things I want to include in v2. I've already implemented the idea in an [experimental branch](https://github.com/reactjs/react-autocomplete/blob/experimental-rewrite/lib/Autocomplete.js#L231).
