### ISSUE TITLE
I think it not work when Autocomplete follow another in the next row

### ISSUE THREAD

**Issue by eruca** [reactjs/react-autocomplete#209]
I write the code like this:
```javascript
<div className='row'>
    <Autocomplete /> //1
</div>
<div className='row'>
    <Autocomplete /> // 2
</div>
```

when I focus the first Autocomplete, the dropdown list  is under the next Autocomplete, the 2 is cover the 1's dropdown list, I think it not work the Autocomplete in a row when another next row

**Comment by CMTegner** [comment]
You probably want to tweak the menu's z-index. You can do so via [`props.menuStyle`](https://github.com/reactjs/react-autocomplete#menustyle-object-optional), or directly on the menu node if you're implementing `props.renderMenu`.
