### ISSUE TITLE
Broken Examples Link in README

### ISSUE THREAD

**Issue by gnarf** [reactjs/react-autocomplete#210]
I'm trying to find your examples but can't.  Please help

**Comment by CMTegner** [comment]
Hi! Yup, looks like reactcommunity.org is down. I've filed [an issue](https://github.com/reactjs/reactjs.github.io/issues/15) with the repo in charge. Thanks for letting us know!

**Comment by ppicazo** [comment]
Links work again: https://github.com/reactjs/reactjs.github.io/issues/15#issuecomment-282955312

**Comment by gnarf** [comment]
Thanks! Looks to be working now!
