### ISSUE TITLE
overlapping 

### ISSUE THREAD

**Issue by araneta** [reactjs/react-autocomplete#212]
it seems the dropdown menu is behind the other component like this https://drive.google.com/file/d/0BzBNRYDFxA9HQnRtRnhwMEdPUnM/view?usp=sharing

**Comment by jonystorm** [comment]
+1

**Comment by CMTegner** [comment]
The default styling preset in `Autocomplete` does not suit every need. If your app's styling scheme uses z-index to position elements along the z-axis you probably need to tweak `Autocomplete`'s styles. Please refer to the [`menuStyle` API documentation](https://github.com/reactjs/react-autocomplete/#menustyle-object-optional).

**Comment by jacobhobson** [comment]
Added the menuStyle object, pasted default settings, and added zIndex I needed:

`menuStyle={{
					borderRadius: '3px',
				  boxShadow: '0 2px 12px rgba(0, 0, 0, 0.1)',
				  background: 'rgba(255, 255, 255, 0.9)',
				  padding: '2px 0',
				  fontSize: '90%',
				  position: 'fixed',
				  overflow: 'auto',
				  maxHeight: '50%', // TODO: don't cheat, let it flow to the bottom
					zIndex: '998',
				}}`

Thanks!
