### ISSUE TITLE
Menu hides behind map component

### ISSUE THREAD

**Issue by agrcrobles** [reactjs/react-autocomplete#219]
I think it will be nice to have a default zIndex: 1 in `menuStyle` to avoid behaviour shown below.
 
![screenshot from 2017-03-30 01-08-29](https://cloud.githubusercontent.com/assets/5727373/24480580/7ef6bb64-14e5-11e7-8d06-c275ccd0bc14.png)

**Comment by CMTegner** [comment]
You have full control over the menu styles in [`menuStyle`](https://github.com/reactjs/react-autocomplete#menustyle-object-optional) and [`renderMenu`](https://github.com/reactjs/react-autocomplete#rendermenu-function-optional). The default menu styles will likely go away in the near future.
