### ISSUE TITLE
Add onBlur property

### ISSUE THREAD

**Issue by vorlov** [reactjs/react-autocomplete#220]
would be nice to have ability to track focus lost event

**Comment by CMTegner** [comment]
You can provide event handlers in [`props.inputProps`](https://github.com/reactjs/react-autocomplete#inputprops-object-optional). Example:

```jsx
<Autocomplete
  inputProps={{ onBlur () { console.log('blur') } }}
/>
```

**Comment by vorlov** [comment]
@CMTegner how to add ref to input so I can control focus?

**Comment by CMTegner** [comment]
There's currently no official way of doing it, but you *can* get to the input element if you add a `ref` on `Autocomplete`:

```jsx
class MyComponent extends Component {
  handleButtonClick () {
    this.input.focus()
  }
  render () {
    return (
      <div>
        <Autocomplete ref={ac => this.input = ac.refs.input } />
        <button onClick={this.handleButtonClick.bind(this)}>Focus input</button>
      </div>
    )
  }
}
```

Keep in mind that **this is unsupported**, so use it at your own risk. v2 will include an imperative API so you can access the common `HTMLInputElement` methods directly from `Autocomplete`.

**Comment by CMTegner** [comment]
Version 1.5.0 has `focus`, `blur`, `setSelectionRange`, and a few other methods you are used to seeing on `<input>` elements. Check the [documentation](https://github.com/reactjs/react-autocomplete/#imperative-api) for an example.
