### ISSUE TITLE
Style values are undefined on renderMenu

### ISSUE THREAD

**Issue by rota-rossi** [reactjs/react-autocomplete#224]
If I start my component with an open attribute, the values for left, top and minWidth are undefined. They are defined only when I click on the input box.

**Comment by CMTegner** [comment]
Thanks for letting us know! It looks like this is due to `setMenuPositions()` only being called in `componentDidUpdate()` and not when the component is initially mounted. I've published a fix for this in 1.4.3. Let us know if you're still experiencing problems with this.
