### ISSUE TITLE
onBlur feature

### ISSUE THREAD

**Issue by tusharchhibber** [reactjs/react-autocomplete#227]
Just out of curiosity, is there a onBlur feature to use for the input textfield here?

**Comment by CMTegner** [comment]
Hi! You can add event handlers such as `onFocus` and `onBlur` by using [`inputProps`](https://github.com/reactjs/react-autocomplete#inputprops-object-optional).

**Comment by tusharchhibber** [comment]
Thank you so much... silly of me...
