### ISSUE TITLE
OnSelect is not called when OnBlur is passed to input props

### ISSUE THREAD

**Issue by vorlov** [reactjs/react-autocomplete#229]
when I pass onBlur event handler to input props, it is called first when I select something from suggestions box, and onSelect is not called then

**Comment by CMTegner** [comment]
Hi! Can you create a reduced test case? I did a simple test but I couldn't reproduce the problem.

**Comment by RikuVan** [comment]
Noticed the same thing here, that is onBlur fires first, then onSelect.

**Comment by vorlov** [comment]
````javascript
<Autocomplete
    ref={ inputRef }
    wrapperStyle={ {
      display: 'block',
      height: '100%',
    } }
    autoHighlight
    items={ items }
    getItemValue={ getItemValue }
    value={ value }
    onChange={ onChange }
    onSelect={ onSelect }
    onBlur={ onBlur }
    renderItem={ renderItem }
    renderMenu={ (renderItems, renderValue) => (
      <div style={ { position: 'relative' } }>
        { loadingAutoComplete && <div className={ styles.autoCompleteMenuNoItems }>Loading...</div> }
        {
          !loadingAutoComplete
          && renderItems.length === 0
          && renderValue.length > 2
          && <div className={ styles.autoCompleteMenuNoItems }>No matches for {value}</div>
        }
        {
          !loadingAutoComplete
          && renderItems.length !== 0
          && renderValue.length > 2
          &&
            <div
              className={ styles.autoCompleteMenu }
              style={ { right: alignRight ? 0 : 'auto' } }
            >
              {renderItems}
            </div>
        }
      </div>
    ) }
    inputProps={ {
      placeholder,
      onBlur,
      onFocus,
      className: styles.autoCompleteInput,
      style: {
        ...inputStyle
      }
    } }
  />````
in that case onSelect is not called, but when I comment onBlur, its working

**Comment by CMTegner** [comment]
I can't really do much with that example since it references so much code which you've omitted. My guess is that `onBlur` in this example modifies some state which triggers a re-render of the `Autocomplete` component, which in turn is preventing `onSelect` from triggering (since the component has been reinstantiated and all previous event handlers have been prevented and removed).

We have logic in place which ensures focus is kept even when the user clicks on an item in the menu, but the native blur and focus events are still triggered. Unfortunately the `onBlur` and `onFocus` where also being triggered. I've fixed this problem in 2a13d56eadbb3dced6a95d01b9cf0bd7ffd323a7 which is a part of 1.5.2. Please update react-autocomplete and see if it solves the problem you were experiencing.

**Comment by RafaelTorres** [comment]
Hi, I have the same problem, currently if I try to select an item from the list when clicking on it, it does not call the onSelect event, and performed several tests such as pressing the enter key on the keyboard or using the selectOnBlur form as well. what if it works, it only fails when I click with the mouse on an item in the list.

I leave an example code of how I am using the component

```
// Component
  getTopBarButtons = () => {

    const autocompleteProps = {
      value: this.state.textToSearch,
      items: Array.isArray( this.props.users ) ? this.props.users : [],
      onSelect: ( value, item ) => console.log( 'onSelect', value, item ), // this.handleItem,
      onChange: this.handleChange,
      renderItem: UserSearchRow,
      wrapperStyle: {
        float: 'right',
      },
      getItemValue: ( item ) => item.username,
      shouldItemRender: () => true,
      renderMenu: ( items ) => (
        <MenuList
          items={items}
          loading={this.props.loadingSearch}
        />
      ),
    }

    return [
      <SearchAutocomplete
        {...autocompleteProps}
      />,
    ]

  }

// Render Menu
class MenuList extends React.Component {

  addkeyToItems = ( items ) => {

    if ( items ) {

      const itemsToRender = items.map( ( item, index ) => ( {
        ...item,
        key: `item-${item.id || index}`,
      } ) )

      return itemsToRender

    }

    return null

  }

  render() {

    const {
      items,
      loading,
    } = this.props

    let ComponentToRender = null

    if ( loading ) {

      ComponentToRender = (
        <LoadingIndicator className={'item-loading-image'} />
      )

    }

    return (
      <div className="menu menu-container">
        {ComponentToRender}
        {this.addkeyToItems( items )}
      </div>
    )

  }

```

Also checking the code I think there is a problem in this event


```
// Extract to documentation in project
selectItemFromMouse(item) {

  const value = this.props.getItemValue(item)
  
  // The menu will de-render before a mouseLeave event
  // happens. Clear the flag to release control over focus
  
  this.setIgnoreBlur(false)
  
  this.setState({
  
    isOpen: false,
    
    highlightedIndex: null
    
  }, () => {
  
    this.props.onSelect(value, item)
    
  })
}
```

Add attachment to have reference

![featured users - google chrome](https://user-images.githubusercontent.com/5580162/38876704-a34efb1e-4222-11e8-9144-fa9ff21f2766.jpg)


References
React version: 15.6.1
React Dom: 15.6.1

**Comment by glocore** [comment]
I'm facing the same issue; doesn't happen when I comment out `onBlur` and `onFocus`. Works when using the arrow keys to select item, but `onSelect` simply doesn't fire when clicking on an item.

@RafaelTorres Were you able to solve this?

**Comment by glocore** [comment]
For me, this was happening because I was programmatically toggling the `open` prop, and due to an implementation detail, `open` would toggle to false before `onSelect`. I gave a 100 ms delay to `onBlur` using `setTimeout` and that seems to have solved the issue.
