### ISSUE TITLE
React.createClass and React.PropTypes are deprecated

### ISSUE THREAD

**Issue by agrcrobles** [reactjs/react-autocomplete#232]
React.createClass and React.PropTypes are deprecated right now and will be removed in version 16.

So there will be need to migrate...

**Comment by ryannjohnson** [comment]
The PR should be ready to go - https://github.com/reactjs/react-autocomplete/pull/231

**Comment by macnibblet** [comment]
Also looking fowarding to not having to scroll in my console history every page load!

**Comment by dimitridewit** [comment]
Might I ask why #231  isn't merged?

**Comment by macnibblet** [comment]
Good question, common hit the merge button :D

**Comment by CMTegner** [comment]
Fixed in 1.5.5.
