### ISSUE TITLE
Add placeholder prop for adding input placeholder

### ISSUE THREAD

**Issue by brettdewoody** [reactjs/react-autocomplete#233]
The <Autocomplete> component should accept a `placeholder` prop for adding a placeholder to the input.

**Comment by CMTegner** [comment]
Hi Brett! This is already available via [`inputProps`](https://github.com/reactjs/react-autocomplete/#inputprops-object-optional):

```jsx
<Autocomplete inputProps={{ placeholder: 'placeholder text' }} />
```

There have been [quite a few](https://github.com/reactjs/react-autocomplete/issues?utf8=%E2%9C%93&q=is%3Aissue%20placeholder) issues filed on this topic, so for v2 we plan on hoisting `inputProps` to the top level (i.e. you'll be able to specify props directly on `Autocomplete` and they'll be passed to `<input>`).
