### ISSUE TITLE
Completely unusable if dependencies are up-to-date

### ISSUE THREAD

**Issue by alexhenrie** [reactjs/react-autocomplete#24]
I installed this component and spent about 4 hours straight trying to make it work, only to finally realize that it is completely unusable with up-to-date dependencies (like you would have if you start writing a React app from scratch with `npm init && npm install --save react react-autocomplete jsx-loader webpack`).

To demonstrate the problem, from a clean clone of react-autocomplete, apply the following patch:

```diff
diff --git a/examples/basic/main.js b/examples/basic/main.js
index 0aaa8b2..4c0d85b 100644
--- a/examples/basic/main.js
+++ b/examples/basic/main.js
@@ -1,7 +1,7 @@
 /** @jsx React.DOM */
 var React = require('react');
-//var Autocomplete = require('react-autocomplete');
-var Autocomplete = require('../../lib/main');
+var Autocomplete = require('react-autocomplete');
+//var Autocomplete = require('../../lib/main');
 var Combobox = Autocomplete.Combobox;
 var ComboboxOption = Autocomplete.Option;
 var states = require('../states');
diff --git a/package.json b/package.json
index 94b06bc..442d330 100644
--- a/package.json
+++ b/package.json
@@ -1,5 +1,5 @@
 {
-  "name": "react-autocomplete",
+  "name": "react-autocomplete-examples",
   "version": "0.0.2",
   "description": "",
   "main": "lib/main.js",
@@ -9,12 +9,13 @@
   "author": "",
   "license": "MIT",
   "dependencies": {
-    "react": "^0.10.0"
+    "react": "^0.12.2",
+    "react-autocomplete": "0.0.2"
   },
   "devDependencies": {
-    "jsx-loader": "^0.10.2",
-    "webpack": "^1.3.0-beta5",
-    "rf-release": "^0.1.2"
+    "jsx-loader": "^0.12.2",
+    "webpack": "^1.6.0",
+    "rf-release": "^0.4.0"
   },
   "tags": [
     "react",
```

Then run `npm install` and `webpack`, open examples/basic/index.html in a browser, and note that the combo box doesn't even appear. Instead, all the options are vomited to the screen with the word UNMOUNTED separating them:

UTALALAlabamaUNMOUNTEDAKAKAlaskaUNMOUNTEDAZAZArizonaUNMOUNTEDARARArkansasUNMOUNTEDCACACaliforniaUNMOUNTEDCOCOColoradoUNMOUNTEDCTCTConnecticutUNMOUNTEDDEDEDelawareUNMOUNTEDFLFLFloridaUNMOUNTEDGAGAGeorgiaUNMOUNTEDHIHIHawaiiUNMOUNTEDIDIDIdahoUNMOUNTEDILILIllinoisUNMOUNTEDININIndianaUNMOUNTEDIAIAIowaUNMOUNTEDKSKSKansasUNMOUNTEDKYKYKentuckyUNMOUNTEDLALALouisianaUNMOUNTEDMEMEMaineUNMOUNTEDMDMDMarylandUNMOUNTEDMAMAMassachusettsUNMOUNTEDMIMIMichiganUNMOUNTEDMNMNMinnesotaUNMOUNTEDMSMSMississippiUNMOUNTEDMOMOMissouriUNMOUNTEDMTMTMontanaUNMOUNTEDNENENebraskaUNMOUNTEDNVNVNevadaUNMOUNTEDNHNHNew HampshireUNMOUNTEDNJNJNew JerseyUNMOUNTEDNMNMNew MexicoUNMOUNTEDNYNYNew YorkUNMOUNTEDNCNCNorth CarolinaUNMOUNTEDNDNDNorth DakotaUNMOUNTEDOHOHOhioUNMOUNTEDOKOKOklahomaUNMOUNTEDOROROregonUNMOUNTEDPAPAPennsylvaniaUNMOUNTEDRIRIRhode IslandUNMOUNTEDSCSCSouth CarolinaUNMOUNTEDSDSDSouth DakotaUNMOUNTEDTNTNTennesseeUNMOUNTEDTXTXTexasUNMOUNTEDUTUTUtahUNMOUNTEDVTVTVermontUNMOUNTEDVAVAVirginiaUNMOUNTEDWAWAWashingtonUNMOUNTEDWVWVWest VirginiaUNMOUNTEDWIWIWisconsinUNMOUNTEDWYWYWyomingUNMOUNTEDUNMOUNTED

Please *at least* put up a big warning that react-autocomplete is incompatible with the current versions of react and jsx-loader, so that no one else tries to use this broken component by mistake.

**Comment by esiqveland** [comment]
+1

**Comment by cgarvis** [comment]
+1

**Comment by EricTill** [comment]
Pretty sure this project is (mostly) abandoned at this point - https://github.com/JedWatson/react-select looks like a much more active project.

**Comment by CMTegner** [comment]
Should be working fine now.
