### ISSUE TITLE
ie11 : clicking on scroll bar closes dropdown

### ISSUE THREAD

**Issue by shrynx** [reactjs/react-autocomplete#248]
Clicking on the scrollbar to drag it down, closes the dropdown and reopens it immediately, without any scroll result
I am adding a gif below. sorry i cut out most part, as i had private data in the list.
![screenflow](https://user-images.githubusercontent.com/4706261/27120046-16aba640-511d-11e7-868e-da5a2f029d56.gif)

**Comment by CMTegner** [comment]
Hi! Which version of `Autocomplete` are you using? We fixed a similar issue in 1.5.3. I can't seem to reproduce this issue on master in IE11 on Windows 10. If you could create a reduced test case it would help a lot!

**Comment by shrynx** [comment]
@CMTegner Windows 8, ie 11. and Autocomplete 1.5.5.

i'll put up a reproducible demo soon.

**Comment by shrynx** [comment]
@CMTegner 
Update:
I fixed it in my code, if am firing ajax for querying and 
whenever i try to scroll ie keeps on keep firing onChange event on empty input.
this behavior is really weird and only happens on empty input. I will further investigate and report back. Closing the issue for now.

**Comment by hari457627** [comment]
Hi i'm using Downshift material ui component. 
scroll bar up and down arrows with mouse clicks is working fine in normal pages,
but its not working in material ui modals.
in modal, when i'm clicking in Downshift suggestions scroll up and right arrow with mouse, then suggestions popup is closing. 
Can anybody help me to solve this issue?
