### ISSUE TITLE
Autoselect (focus lost)

### ISSUE THREAD

**Issue by matiwinnetou** [reactjs/react-autocomplete#251]
For our usecase we actually need that blur or focuslost causes the value in dropdown to be preselected when user leaves the field.

The idea is that some users when item is highlighted may think it is preselected.

**Comment by SergeyShvager** [comment]
Totally agree! We have the same use case. Would be awesome to add new feature under prop `autoSelect`. I would like to make contribution with this new feature.

**Comment by CMTegner** [comment]
>For our usecase we actually need that blur or focuslost causes the value in dropdown to be preselected when user leaves the field.

Is this for when the user navigates between input elements by using `Tab`, or for when they click outside the input? The former has already been proposed and will likely be implemented in v2, but the latter seems like very confusing behaviour to me. A good UX benchmark is to look at how the native `<select>` element behaves in similar situations.

>The idea is that some users when item is highlighted may think it is preselected.

Is this a theory you have, or have you proven it through user testing?

**Comment by matiwinnetou** [comment]
We have proven it via A/B testing. We had a few variants, this one performed the best. 

You can play with old jQuery component which we are rewriting now on our page and you can see that it is currently selecting items on focus lost (both tab and click out).

![image](https://user-images.githubusercontent.com/335933/27508262-3daa0626-58e1-11e7-8baa-e8e336af71fe.png)

https://suchen.mobile.de/fahrzeuge/search.html?lang=en

**Comment by CMTegner** [comment]
Closed via #252. Thanks for the work!
