### ISSUE TITLE
How to access keyCode from input value

### ISSUE THREAD

**Issue by charlieroth** [reactjs/react-autocomplete#263]
This isn't really an issue with react-autocomplete itself but I was wondering how I can access the keyCode value from the input element that is generated by the AutoComplete component?

**Comment by CMTegner** [comment]
Hi Charles! First you need to figure out which event you want to listen to to intercept the keyboard event. You're probably after `keyDown`, in which case you can use `props.inputProps.onKeyDown`. All valid event handlers found in [`props.inputProps`](https://github.com/reactjs/react-autocomplete#inputprops-object-optional) are attached to the `<input>` element generated by `Autocomplete`, and work just like you would expect (i.e. they receive the event object as their sole argument).

Hope this was what you were after!
