### ISSUE TITLE
Input search for non existing value displays not required blank drop-down menu in IE11

### ISSUE THREAD

**Issue by rapaSharma** [reactjs/react-autocomplete#264]
Issue is in IE. In Chrome it works fine.
1. Search for item starts with cumaa295(more than 5 items exists in list) displays drop-down of 3 values with scrollbar.
2. Search for item starts with cumaa295**2**(not exists in list) displays blank drop-down menu
Note: If drop-down list having no scroll bar works fine.

![image](https://user-images.githubusercontent.com/30756004/28998212-fe6e1fc8-7a42-11e7-97c7-5b0e37fcb8b5.png)

Same issue can be notice using one of the example given in react-autocomplete code page.
i.e., [https://reactcommunity.org/react-autocomplete/async-data/](url)
![image](https://user-images.githubusercontent.com/30756004/28998762-8494020e-7a50-11e7-858a-1d54d0098e51.png)

**Comment by CMTegner** [comment]
This is an issue with `max-height`. Try removing `max-height` from the menu styles and see if it fixes the problem.

**Comment by rapaSharma** [comment]
Not worked for me. Still same issue.

**Comment by rapaSharma** [comment]
overflow:"scroll" will work. But, it brings unnecessary Scroll all time :(

**Comment by CMTegner** [comment]
Can you create a reduced test case (like a JSFiddle) where you remove `max-height` and still see the problem?

**Comment by rapaSharma** [comment]
I will provide JSFiddle with specific example. Meanwhile, you can test example given by you about Async data only.

**Comment by rapaSharma** [comment]
Issue was with width attribute. Below solution helped in get rid of this issue.

Solution: menuStyle={ itemsCount <= 0 ? {} : menuStyle }
