### ISSUE TITLE
autoHighlight={true} only highlights the first item - if it matches from its beginning

### ISSUE THREAD

**Issue by silicakes** [reactjs/react-autocomplete#266]
**autoHighlight={true} only highlights the first item if it matches from its beginning**

Here's an example for when it doesn't work:
1. user inputs: "foo"
2. multiple choices for items containing the word "blah blah food" are shown
3. first item isn't highlighted

It does work for the following:
1. user inputs "foo"
2. multiple choices begin with . "food"
3. first item is highlighted

**Comment by CMTegner** [comment]
This is explained in #239.
