### ISSUE TITLE
Is it possible to have a label and a value?

### ISSUE THREAD

**Issue by psyanite** [reactjs/react-autocomplete#267]
For example, I would like to display a list of Areas,
[
{ label: "Kansas", value: "1" },
{ label: "Texas", value: "2" }
]

Sorry, if I've missed this from the documentation :(

Thank you for taking the time to read my question :)

**Comment by CMTegner** [comment]
Hi! Did you figure it out on your own?

**Comment by psyanite** [comment]
Hey @CMTegner, that's probably one of the fastest responses I've seen on Github so far. I love this project. 

Turns out I was just being a dummy. I figured it out by passing an object with three properties, namely `kind`, `name`, and `value`, and displaying only `name`. 

Thanks for responding even though I closed the issue.

**Comment by CMTegner** [comment]
Great, glad you figured it out :)
