### ISSUE TITLE
Suggestion: Display examples on codepen

### ISSUE THREAD

**Issue by psyanite** [reactjs/react-autocomplete#268]
I see there are lovely examples no reactcommunity but it would really benefit a newbie like me if these had a codepen as well :) If it's not too difficult to do that is.

Thank you! 🍰

**Comment by CMTegner** [comment]
I added a link to an example in JSBin in the README. Hope this helps!

**Comment by psyanite** [comment]
@CMTegner that is sweet!!! Makes it so quick to play around straight away. I also didn't realise you could look at the code inside the `examples` folder, but it made a lot more sense after looking at em.

:cake:
