### ISSUE TITLE
Cannot set an id on the autocomplete component

### ISSUE THREAD

**Issue by john1625b** [reactjs/react-autocomplete#269]
When I try to do something like this:
`<Autocomplete id='auto-complete' />`
The actual input element that is rendered does not have an id. I need an id on the input because I am trying to target it with a label, like so
`<label for='auto-complete'/>`

**Comment by CMTegner** [comment]
Hi John! You can use [`inputProps`](https://github.com/reactjs/react-autocomplete#inputprops-object-optional) to pass any prop to the `<input>` component. Hope this helps :)
