### ISSUE TITLE
Usage with botframework webchat

### ISSUE THREAD

**Issue by ramgesg** [reactjs/react-autocomplete#274]
Can you suggest an approach where this can be implemented in the [Webchat](https://github.com/Microsoft/BotFramework-WebChat)

**Comment by CMTegner** [comment]
Hi Ramakrishnan! We try to keep the GH issue tracker narrowed down to bugs, improvements, and usability issues. Implementation help like you are requesting is probably better suited for a forum like StackOverflow. Try using the javascript and react tags there to find/request help!
