### ISSUE TITLE
Add className, style as props

### ISSUE THREAD

**Issue by Fralleee** [reactjs/react-autocomplete#279]
Add className and style as props for easier customization.

**Comment by CMTegner** [comment]
_Please_ read the documentation:

* [`renderItem`](https://github.com/reactjs/react-autocomplete#renderitem-function)
* [`inputProps`](https://github.com/reactjs/react-autocomplete#inputprops-object-optional)
* [`menuStyle`](https://github.com/reactjs/react-autocomplete#menustyle-object-optional)
* [`renderInput`](https://github.com/reactjs/react-autocomplete#renderinput-function-optional)
* [`renderMenu`](https://github.com/reactjs/react-autocomplete#rendermenu-function-optional)
* [`wrapperProps`](https://github.com/reactjs/react-autocomplete#wrapperprops-object-optional)
* [`wrapperStyle`](https://github.com/reactjs/react-autocomplete#wrapperstyle-object-optional)
