### ISSUE TITLE
onSelect() being executed 2 times.

### ISSUE THREAD

**Issue by juampick** [reactjs/react-autocomplete#283]
Hi! 

I updated the library to: `@1.7.2` also together with React16. I've started to experience some strange issue that the `onSelect()`is being call also when I didn't select it.

Does anyone have the same issue? Thanks a lot,

Juan

**Comment by CMTegner** [comment]
Hi Juan! You'll have to provide some more information if we're going to be able to debug the problem. Can you create a reduced test case in a gist and/or jsfiddle?

**Comment by juampick** [comment]
Hi @CMTegner ... Sorry about my delay and thanks for your help.

I've just created an isolated test on this JSBIN: http://jsbin.com/kicocuj/2/edit?html,js,console,output.
And realized that work ok using React 16 and latest @1.7.2 version of react-autocomplete. 

That's why checked and we had an issue with our code. 

Thanks a lot for your help, and sorry for that.

Juan
