### ISSUE TITLE
Suggestions are scrolled with the window

### ISSUE THREAD

**Issue by divined** [reactjs/react-autocomplete#284]
Suggestions are scrolled with the window.

**Comment by AlexPoirier1** [comment]
Issue should be renamed to the actual problem (`Suggestions are scrolled with the window`)

**Comment by AlexPoirier1** [comment]
I have worked around this issue by adding a scroll listener that re-focus the input when scrolling ends.
It is superbly hackish but it does not mess with the CSS so that when the issue is fixed, it shouldn't make it completly bug out.

```js
componentWillMount() {
	window.addEventListener('scroll', this.handleScroll);
}

componentWillUnmount() {
	window.removeEventListener('scroll', this.handleScroll);
}

isElementVisible(ref) {
	const bottom = ref.getBoundingClientRect().bottom;
	return (bottom > 0 && bottom < window.innerHeight);
}

handleScroll() {
	if(this.input.isOpen() && this.isElementVisible(this.input.refs.input)) {
		this.input.blur();
		clearTimeout(this.scrolling_timeout);
		this.scrolling_timeout = setTimeout(() => {
			if(this.isElementVisible(this.input.refs.input)) {
				this.input.focus();
			}
		}, 250);
	}
}
```

Assuming `this.input` is the ref to the actual auto-complete component.
```
<Autocomplete
	ref={el => (this.input = el)}
```

**Comment by divined** [comment]
ty

**Comment by CMTegner** [comment]
Just set the menu's position to `absolute`, and the wrapper to `relative`:

```jsx
<Autocomplete
    wrapperStyle={{ position: 'relative' }}
    menuStyle={{ position: 'absolute' }}
/>
```

This will affix the menu to the bottom of the input.

**Comment by illiptic** [comment]
You also need to set top and left properties on the menu, to override the default positioning.
(change top to suit the height of your input)
```
<Autocomplete
    wrapperStyle={{ position: 'relative' }}
    menuStyle={{ position: 'absolute', top: '35px', left: 0 }}
/>
