### ISSUE TITLE
Strange work isHighlighted

### ISSUE THREAD

**Issue by AlexandrAnash** [reactjs/react-autocomplete#288]
https://reactcommunity.org/react-autocomplete/custom-menu/

when I type 'a' I see highlighted
https://cloud.mail.ru/public/2Pts/PUP1mFxSn

But I type 'b' I don't see highlighted
https://cloud.mail.ru/public/Ke7j/ciYvvcQN1

Really wanted to manage when to highlight the first item, and when not
This is possible?

**Comment by Slogo** [comment]
I think this is the issue described by https://github.com/reactjs/react-autocomplete/issues/239

**Comment by CMTegner** [comment]
We don't currently offer a way to directly manipulate which item gets highlighted. We plan on reworking this logic for v2.
