### ISSUE TITLE
How to get highlighted item

### ISSUE THREAD

**Issue by LekovicMilos** [reactjs/react-autocomplete#291]
Hi guys,

I have a problem with getting the currently highlighted item. Is there a way to do that at all? I want to change the value of input with highlighted item's value, while I press keys Up and Down. I don't see anywhere callback function or smt, to put ref on the highlighted item. Do you have suggestion how to do that?

Thanks in advance!

**Comment by quachsimon** [comment]
I'm not sure how you would get the highlighted item but, if you open the React console log (in Chrome) you can see that the component has a state called `highlightedIndex`which indicates the value that is higlighted.

**Comment by LekovicMilos** [comment]
I've got it in this.input.state.highlightedIndex, thanks! Now, I need another thing. How can I keep the menu opened after changing the value fo the input?

**Comment by LekovicMilos** [comment]
You helped me, so I am closing this issue. The problem that I have with menu being open after value change is on this url now: https://github.com/reactjs/react-autocomplete/issues/292
