### ISSUE TITLE
'value' is not defined

### ISSUE THREAD

**Issue by francisrod01** [reactjs/react-autocomplete#297]
The doc example doesn't work.

```js
<Autocomplete
  getItemValue={(item) => item.label}
  items={[
    { label: 'apple' },
    { label: 'banana' },
    { label: 'pear' }
  ]}
  renderItem={(item, isHighlighted) =>
    <div style={{ background: isHighlighted ? 'lightgray' : 'white' }}>
      {item.label}
    </div>
  }
  value={value}
  onChange={(e) => value = e.target.value}
  onSelect={(val) => value = val}
/>
```

These last 3 lines don't work.
I think the doc will be improved. :+1:

**Comment by CMTegner** [comment]
This is just pseudo code to give a rough idea of how much work is involved in a minimal implementation. While this may be confusing to people who are new to React, I think it's fairly obvious for most React developers that it's an incomplete example. There are plenty of [working examples](https://reactcommunity.org/react-autocomplete/) - including an [online editor](http://jsbin.com/mipesawapi/edit?js,output) - where you can copy implementations from.

**Comment by francisrod01** [comment]
Well, I cannot learn more about it if this docs are pool about this implementation.
So.. thank for al!

**Comment by CMTegner** [comment]
It is not the responsibility of this repository to teach you about React or JavaScript. There are countless resources available on either of these topics.

I don't appreciate your tone in your last reply. I'm using my spare time to try to maintain a codebase which is free to use. I do not wish to receive snarky comments when I have clearly outlined my reasoning.

I'm locking this thread. Feel free to submit a PR if you want to improve the documentation.
