### ISSUE TITLE
clicking the down arrow twice should close the menu?

### ISSUE THREAD

**Issue by petehunt** [reactjs/react-autocomplete#3]
I think the right behavior when clicking the arrow while the menu is open is to close the menu, right?

**Comment by sprjr** [comment]
@petehunt @ryanflorence not sure I follow, this is an older issue so it may not still apply. There's an event handler now for navigating through the menu items via the down arrow that actually circles back through the options when you reach the end. Mind expanding a bit more if you still think there's behavior to add here?

**Comment by CMTegner** [comment]
@sprjr this discussion happened when there was an actual arrow icon in the input field :) Added in 8fd161c36ee701d360e279332d49d866cc08e402 and removed in a5ea0b72aaed2c9a29105f348624892d379d5b3d.
