### ISSUE TITLE
Adding `menuProps` or `menuClassName` to better customize the menu style.

### ISSUE THREAD

**Issue by sergiop** [reactjs/react-autocomplete#300]
I'm using JSS instead of inline styles, and without accessing to `className` prop, I can't integrate JSS object in menu.

Currently I can do it with `input`:
```JSX
inputProps={{
  className: classes.input, // JSS style class name
}}
```
And with `wrapper`:
```JSX
inputProps={{
  className: classes.wrapper, // JSS style class name
}}
```

But there is no possibility to access to `menu` element to manage `className` prop.

**Comment by CMTegner** [comment]
Hi Sergio! You can use [`renderMenu`](https://github.com/reactjs/react-autocomplete#rendermenu-function-optional) to achieve this. We're looking to reduce the amount of element-specific props in favour of render callbacks, so we won't be adding a new prop for this at the moment.
