### ISSUE TITLE
It would be nice to make an additional parameter for key={...}

### ISSUE THREAD

**Issue by AlexandrAnash** [reactjs/react-autocomplete#306]
It would be nice to make an additional parameter
example 
```
renderItem={(item, isHighlighted, style, **index**) => ()
```
Because you do not always want to specify a unique **key**
Either make the default key={index} if key == null

In all examples, a key is prescribed by the hands :(
```
renderItem={(item, isHighlighted) => (
            <div
              className={`item ${isHighlighted ? 'item-highlighted' : ''}`}
              key={item.abbr}
            >{item.name}</div>
          )}
```

**Comment by GDR** [comment]
[Don't use index as key
](https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318)

**Comment by AlexandrAnash** [comment]
Thank!
