### ISSUE TITLE
ARIA-control for added Accessibility 

### ISSUE THREAD

**Issue by jackmallahan** [reactjs/react-autocomplete#311]
### Improvement for Accessibility

* Add a hidden aria-live div that sends a message to screen reader about the results of auto-complete e.g. '{results} results displayed'
* Add aria-control to auto-complete to update on every character.

**Comment by CMTegner** [comment]
Hi Jack! Seems like you know a thing or two about a11y, mind giving us a hand by submitting a PR?

**Comment by jackmallahan** [comment]
There seems to be a deeper issue with 'aria-live' that is causing interruptions. I am going to close this issue since the only way to resolve this issue is with logic that doesn't need to live inside of this component.
