### ISSUE TITLE
React and autocomplete when I already have a text box

### ISSUE THREAD

**Issue by AllanCodes** [reactjs/react-autocomplete#319]
Hello, I have this React render() function.

 ```
 render() {
    return (
      <div className='Filter'>
        <ul id='settings'>
          <li id='filterSetting'>
            <label htmlFor='sefs'>Filter:</label>
            <input type='text' id='sefs'
              onBlur={ (e) => this.vars.inputString = e.target.value }
            />
          </li>
    );
  }
```

I'd like to place my autosuggest to be connected with the Filter: input box.  How can I do this?  I'm fairly new to React and do not understand where this should be placed and how to connect the variables to it.  Help appreciated!  Thanks.

**Comment by CMTegner** [comment]
Hi Allan! I suggest posting this question on [StackOverflow](https://stackoverflow.com/questions/tagged/reactjs) to see if anyone is able to help you reach your desired goal. We're not really equipped to teach React fundamentals or help design apps here. Hope you understand!
