### ISSUE TITLE
Set max size of the visible items

### ISSUE THREAD

**Issue by stanyq4** [reactjs/react-autocomplete#320]
Is there an out of the box solution to set the max number of visible items in the drop-down? 

Would be great to in case the item list is getting too big.

**Comment by CMTegner** [comment]
If you want a visual limit you can set `max-height` on the dropdown menu via CSS. If you want to limit the number of items rendered I suggest filtering the list of `items` outside of `Autocomplete` instead of specifying the `shouldItemRender` prop.

**Comment by miles-crighton** [comment]
I found a little workaround to limit the children rendered in the menu using this prop:
```
renderMenu={ children => (
    <div className= "menu">
       {children.slice(0, maxMenuItems)}
    </div>
)}
```
Not sure if there are any issues with this.
