### ISSUE TITLE
Set placeholder

### ISSUE THREAD

**Issue by saidmoya12** [reactjs/react-autocomplete#34]
How can I set placeholder and other options in placeholder?

In the code I cannot see that option

Thanks

**Comment by leverage7** [comment]
Currently, I am doing this --

inputProps={{ placeholder: 'placeholder text' }}

**Comment by xjamundx** [comment]
thank you!

**Comment by laughnan** [comment]
This also worked for me! Thanks @benbruning !

**Comment by ivishwas-s** [comment]
Thanks @benbruning

**Comment by anirudh9654** [comment]
Can we only pass string as placeholer ?
