### ISSUE TITLE
Android: Delete doesn't work as expected

### ISSUE THREAD

**Issue by connorjburton** [reactjs/react-autocomplete#40]
#Nexus 5, delete issue

It's hard to show this issue but I have captured it via USB debugging. When you try and delete the last letter it doesn't change the value, then (seemingly) randomly after a certain amount of attempts it will delete the whole field.

You can see on the right hand side when the elements flash I am typing in the box.

![react-autocomplete](https://cloud.githubusercontent.com/assets/10538031/9235846/349fc2da-4139-11e5-958a-13caf7ab134b.gif)

**Comment by connorjburton** [comment]
Only thing I can work out from this is that you are deleting the letters but the auto fill just puts the first matched value back in.

So the only time you can delete the whole word is when you delete it fast enough, maybe? Not sure on that last theory

**Comment by ianhattendorf** [comment]
This is happening to me as well.

I also have to tap each letter on the keyboard multiple times before it will enter. This happens with both static and async data.
