### ISSUE TITLE
Migrate to rackt eslint config

### ISSUE THREAD

**Issue by pwmckenna** [reactjs/react-autocomplete#57]
https://github.com/rackt/eslint-config-rackt contains a starting point that all org repos can build off of. This can be introduced by first using the config and overriding any rules that the repo doesn't comply with, without having to change any of the source. Then for non-controversial rules, PRs can be made to update the source to comply.

Here's the initial PR: https://github.com/rackt/react-autocomplete/pull/55

**Comment by CMTegner** [comment]
Merged!
