### ISSUE TITLE
Why inline-block?

### ISSUE THREAD

**Issue by docentq2** [reactjs/react-autocomplete#66]
https://github.com/rackt/react-autocomplete/blob/master/lib/Autocomplete.js#L301

Hi.
If I want make this div display block? How I make it, without change code in node_modules?

**Comment by otmjka** [comment]
PR, please ^_^ https://github.com/rackt/react-autocomplete/pull/50

**Comment by docentq2** [comment]
@otmjka thanks!

**Comment by robcalcroft** [comment]
+1

**Comment by skeie** [comment]
+1

**Comment by NerdHerd91** [comment]
+1 just got but by this today, had to use selectors to target that div for adjustments

**Comment by raffe90** [comment]
+1

**Comment by lioramsalem90** [comment]
+1

**Comment by hontas** [comment]
The autocomplete build in `./build/lib/Autocomplete.js` is broken.
It always sets display to 'inline-block' and not to passed property `wrapperStyles`.
When I build locally with `rackt build` it turns out fine - so a new build should resolve this.

**Comment by laughnan** [comment]
Has this been resolved or investigated? I'm seeing the same issue.

**Comment by hontas** [comment]
just made a PR to resolve this: #97

**Comment by Jhays10** [comment]
For a quick fix, I found if you pass `wrapperStyle={{}}` in as a prop, that will remove the `inline-block`.

Example:
```
<Autocomplete
  value={s.value}
  items={s.options}
  getItemValue={this.getItemValue}
  onSelect={p.onSelect}
  onChange={this.handleChange}
  renderItem={this.renderItem}
  renderMenu={this.renderMenu}
  wrapperStyle={{}} />
```

**Comment by hontas** [comment]
@Jhays10 take a look @ https://github.com/reactjs/react-autocomplete/blob/master/build/lib/Autocomplete.js#L303 and tell me how that is possible. As you can see, inline-block i hard-coded in current build, something my PR above fixes. I'm just waiting for someone to merge it since I can't.

**Comment by Jhays10** [comment]
@hontas The `wrapperStyle` is set in the `getDefaultProps`.
https://github.com/reactjs/react-autocomplete/blob/master/lib/Autocomplete.js#L26

So when you specify `wrapperStyle={{}}` your removing that default and setting it to your own empty object. To fix this, I would expect `getDefaultProps` to set `wrapperStyle: {}`.

**Comment by hontas** [comment]
@Jhays10 yes I know. But when you require react-autocomplete you get the built file, specified in package.json as main. Take a look at the code there and you'll see that it's not the same and that's why I made a PR with a new build to fix this.

**Comment by docentq2** [comment]
https://github.com/reactjs/react-autocomplete/pull/50

**Comment by Messhias** [comment]
There's a way to remove that div? I don't want it and I don't need it. It's breaking my sass.
