### ISSUE TITLE
Transfer to reactjs

### ISSUE THREAD

**Issue by mjackson** [reactjs/react-autocomplete#72]
We're merging @rackt with the @reactjs GitHub org. Just wanted to let everyone know we'll be transferring this repo over there.

**Comment by lachlanjc** [comment]
That's great @mjackson! The demo link is 404'ing now though :neutral_face:

**Comment by mjackson** [comment]
Thanks for the heads up @lachlanjc. We're working on getting a new domain setup. See https://github.com/reactjs/reactjs.github.io/issues/13
