### ISSUE TITLE
'No matches for' after blur and focus on input

### ISSUE THREAD

**Issue by bekerov** [reactjs/react-autocomplete#81]
Not useful
![image](https://cloud.githubusercontent.com/assets/2405629/13667945/4741d284-e6ca-11e5-82a2-2d60e757017c.png)

**Comment by CMTegner** [comment]
Could you please provide the required steps to reproduce the issue you're seeing?

**Comment by bekerov** [comment]
1. Go to https://reactcommunity.org/react-autocomplete/custom-menu/
2. Enter or choose 'Alabama'.
3. Click outside field
4. Click on input.

**Comment by CMTegner** [comment]
Thanks! I was able to reproduce the issue and create a fix.
