### ISSUE TITLE
Isomorphic rendering broken

### ISSUE THREAD

**Issue by thebigredgeek** [reactjs/react-autocomplete#86]
https://github.com/reactjs/react-autocomplete/blob/master/lib/Autocomplete.js#L52 < This seems problematic...  Obviously the same ID won't exist on both sides of the pipe

**Comment by danielfalk** [comment]
Can confirm as it happens to me.  Relevant line has shifted, so here's a more stable link:

https://github.com/reactjs/react-autocomplete/blob/6c7a7cfe15b161187a7c802eb0e19c257aaab20c/lib/Autocomplete.js#L52

**Comment by danielfalk** [comment]
This is the same as the problem reference here: https://github.com/facebook/react/issues/5867

**Comment by CMTegner** [comment]
This was fixed in #89. Should work fine in 1.0.0-rc4.
