### ISSUE TITLE
Order of typed text scrambled on IE10 and 11

### ISSUE THREAD

**Issue by pdc** [reactjs/react-autocomplete#96]
I am on Windows 8.2 with IE in either Edge or IE10 mode.

When I visit <https://reactcommunity.org/react-autocomplete/static-data/> and type `nebr`, 
I see a flash of the autocomplete menu and then the text box contains `ebrn`.

**Comment by CMTegner** [comment]
This was fixed in #85, should be working in 1.0.0-rc4. reactcommunity.org hasn't been updated yet.
